In [5]:
from sklearn.linear_model import LinearRegression
import numpy as np

In [7]:
x = np.arange(10).reshape(-1,1)

y = (2*x + 1).reshape(-1,1)

In [8]:
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [9]:
y

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19]])

In [10]:
model = LinearRegression() # 모델선언

In [11]:
model

LinearRegression()

In [12]:
model.fit(x, y) # 학습

LinearRegression()

In [13]:
prediction = model.predict([[10.0]]) # 에측

In [14]:
prediction 

array([[21.]])